In [37]:
import os
import glob
from functools import reduce

In [38]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import seaborn as sns

# display plots in the notebook
%matplotlib inline

# increase default figure and font sizes for easier viewing
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['font.size'] = 14

## Analysis
---

Description: This is a test for broker evaluation with varying number of subscribers and publishers. The broker process -- along with all its threads -- is pinned to a single physical core (core 9). The interval is set to 1ms (e.g., no. of pubs * 1000rps).

In [39]:
results_dir = "../../../results/broker/hosts/"
date_time_list = ["20170731231815.490819", "20170801000044.280947"]

cols = ['%cpu', '%mem']

In [40]:
broker_data_dict = {}

for date_time in date_time_list:
    for i in glob.glob(results_dir + date_time + "/broker_stats_with__*"):
        key = i.split('__')[1].split('_')[1] + "x" + i.split('__')[2].split('_')[1]        
        broker_data_dict[key] = pd.read_csv(i, sep=' ', header=None, na_filter=False, names = cols)

# sorted(broker_data_dict.keys())

In [41]:
pcpu_usage = pd.DataFrame()

cols = [1, 2, 4, 8, 16, 32, 64, 128]

pcpu_usage['pubs'] = cols

for col in cols:
    row = []
    for i in pcpu_usage['pubs']:
        if str(i) + "x" + str(col) in broker_data_dict:
            row += [broker_data_dict[str(i) + "x" + str(col)]['%cpu'].mean()]
        else:
            row += [np.nan]
    pcpu_usage['%pcpu' + "-subs:" + str(col)] = row

pcpu_usage = pcpu_usage.set_index('pubs')
    
pcpu_usage

,%pcpu-subs:1,%pcpu-subs:2,%pcpu-subs:4,%pcpu-subs:8,%pcpu-subs:16,%pcpu-subs:32,%pcpu-subs:64,%pcpu-subs:128
pubs,,,,,,,,
1,5.227273,5.618182,6.481818,7.945455,10.836364,16.572727,27.872727,49.991667
2,7.672727,9.209091,8.981818,12.830000,17.250000,27.430000,46.172727,87.045455
4,11.600000,13.480000,14.727273,20.240000,28.300000,46.454545,88.390909,99.945455
8,20.754545,24.090909,26.430000,35.500000,51.400000,83.581818,99.545455,NaN
16,34.090909,39.560000,48.300000,65.660000,97.050000,99.954545,NaN,NaN
32,54.600000,63.245455,82.709091,99.945455,NaN,NaN,NaN,NaN
64,99.972727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
pmem_usage = pd.DataFrame()

cols = [1, 2, 4, 8, 16, 32, 64, 128]

pmem_usage['pubs'] = cols

for col in cols:
    row = []
    for i in pmem_usage['pubs']:
        if str(i) + "x" + str(col) in broker_data_dict:
            row += [broker_data_dict[str(i) + "x" + str(col)]['%mem'].mean()]
        else:
            row += [np.nan]
    pmem_usage['%pmem' + "-subs:" + str(col)] = row

pmem_usage = pmem_usage.set_index('pubs')
    
pmem_usage

,%pmem-subs:1,%pmem-subs:2,%pmem-subs:4,%pmem-subs:8,%pmem-subs:16,%pmem-subs:32,%pmem-subs:64,%pmem-subs:128
pubs,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
16,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
32,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
64,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN